# <a id='toc1_'></a>[Tutorial - Udemy - Programmer en Python pour la Data Science de A à Z](#toc0_)
**Objective : Hands one in Numpy, Pandas and Matplotlib libraries**

**Table of contents**<a id='toc0_'></a>    
- [Tutorial - Udemy - Programmer en Python pour la Data Science de A à Z](#toc1_)    
  - [Exploring Series](#toc1_1_)    
  - [Exploring Pandas](#toc1_2_)    
    - [Remove null values in dataframe](#toc1_2_1_)    
  - [Sort dataframe](#toc1_3_)    
  - [Conversion data in dataframe](#toc1_4_)    
  - [Filter in dataframe](#toc1_5_)    
  - [Group a column in dataframe](#toc1_6_)    
- [Exercice :](#toc2_)    
    - [Quels sont les noms, les catégories et les genres des applications les plus installées sur Google Play ?](#toc2_1_1_)    
    - [Quel est le plus grand nombre de Reviews ? (avis) Quel est le nom et la note globale de l’application concernée ?](#toc2_1_2_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

## <a id='toc1_1_'></a>[Exploring Series](#toc0_)

In [1]:
import pandas as pd
import numpy as np

In [2]:
serie = pd.Series([17, 24, 32, 40, 51,1])
print(serie)

# replace index serie with names
serie.index = ['Fred', 'beatrice', 'carole', 'dédé', 'egueune', 'fabrice']
print(serie)
serie.describe()

0    17
1    24
2    32
3    40
4    51
5     1
dtype: int64
Fred        17
beatrice    24
carole      32
dédé        40
egueune     51
fabrice      1
dtype: int64


count     6.000000
mean     27.500000
std      17.626684
min       1.000000
25%      18.750000
50%      28.000000
75%      38.000000
max      51.000000
dtype: float64

In [3]:
# Read the csv file by using nmumpy 
houses = np.genfromtxt('Houses.csv', delimiter=',', dtype=int, encoding='utf-8')
print(houses)

[[212000   4148  25264]
 [230000   2501  11891]
 [339000   4374  25351]
 [289000   2398  22215]
 [160000   2536   9234]
 [ 85000   2368  13329]
 [ 85000   1264   8407]
 [145000   1572  12588]
 [164000   2375  16204]
 [123500   1161   9626]
 [180000   1542   8755]
 [159500   1464  14636]
 [156000   2240  21780]
 [146500   1269  11250]
 [101500    924   7361]
 [109800    768  10497]
 [182000   1320  15768]
 [110000   1845  12153]
 [125000   1274  13634]
 [ 80000   1905  10890]]


In [4]:
df_houses = pd.DataFrame(houses, columns=['Prix', 'Taille de la maison', 'Surface'])
df_houses

Prix  Taille de la maison  Surface
0   212000                 4148    25264
1   230000                 2501    11891
2   339000                 4374    25351
3   289000                 2398    22215
4   160000                 2536     9234
5    85000                 2368    13329
6    85000                 1264     8407
7   145000                 1572    12588
8   164000                 2375    16204
9   123500                 1161     9626
10  180000                 1542     8755
11  159500                 1464    14636
12  156000                 2240    21780
13  146500                 1269    11250
14  101500                  924     7361
15  109800                  768    10497
16  182000                 1320    15768
17  110000                 1845    12153
18  125000                 1274    13634
19   80000                 1905    10890

## <a id='toc1_2_'></a>[Exploring Pandas](#toc0_)

In [5]:
# Create Dataframe from series
group1 = pd.Series([11, 21, 31, 41, 51], index=['a', 'b', 'c', 'd', 'e'])
group2 = pd.Series([60, 70, 80, 90, 10], index=['alix', 'baa', 'c', 'd', 'edil'])
df_group = pd.DataFrame({'group1': group1, 'group2': group2})
df_group

group1  group2
a       11.0     NaN
alix     NaN    60.0
b       21.0     NaN
baa      NaN    70.0
c       31.0    80.0
d       41.0    90.0
e       51.0     NaN
edil     NaN    10.0

In [6]:
# Read the csv file by using pandas
df_google_apps = pd.read_csv('googleplaystore.csv')
df_google_apps

# Write a csv file
df_google_apps.to_csv('googleplaystore_copy.csv', index=False)

df_google_apps_index = df_google_apps.set_index('App')

df_google_apps_index

Category  \
App                                                                       
Photo Editor & Candy Camera & Grid & ScrapBook           ART_AND_DESIGN   
Coloring book moana                                      ART_AND_DESIGN   
U Launcher Lite – FREE Live Cool Themes, Hide Apps       ART_AND_DESIGN   
Sketch - Draw & Paint                                    ART_AND_DESIGN   
Pixel Draw - Number Art Coloring Book                    ART_AND_DESIGN   
...                                                                 ...   
Sya9a Maroc - FR                                                 FAMILY   
Fr. Mike Schmitz Audio Teachings                                 FAMILY   
Parkinson Exercices FR                                          MEDICAL   
The SCP Foundation DB fr nn5n                       BOOKS_AND_REFERENCE   
iHoroscope - 2018 Daily Horoscope & Astrology                 LIFESTYLE   

                                                    Rating Reviews  \
App                                                                  
Photo Editor & Candy Camera & Grid & ScrapBook         4.1     159   
Coloring book moana                                    3.9     967   
U Launcher Lite – FREE Live Cool Themes, Hide Apps     4.7   87510   
Sketch - Draw & Paint                                  4.5  215644   
Pixel Draw - Number Art Coloring Book                  4.3     967   
...                                                    ...     ...   
Sya9a Maroc - FR                                       4.5      38   
Fr. Mike Schmitz Audio Teachings                       5.0       4   
Parkinson Exercices FR                                 NaN       3   
The SCP Foundation DB fr nn5n                          4.5     114   
iHoroscope - 2018 Daily Horoscope & Astrology          4.5  398307   

                                                                  Size  \
App                                                                      
Photo Editor & Candy Camera & Grid & ScrapBook                     19M   
Coloring book moana                                                14M   
U Launcher Lite – FREE Live Cool Themes, Hide Apps                8.7M   
Sketch - Draw & Paint                                              25M   
Pixel Draw - Number Art Coloring Book                             2.8M   
...                                                                ...   
Sya9a Maroc - FR                                                   53M   
Fr. Mike Schmitz Audio Teachings                                  3.6M   
Parkinson Exercices FR                                            9.5M   
The SCP Foundation DB fr nn5n                       Varies with device   
iHoroscope - 2018 Daily Horoscope & Astrology                      19M   

                                                       Installs  Type Price  \
App                                                                           
Photo Editor & Candy Camera & Grid & ScrapBook          10,000+  Free     0   
Coloring book moana                                    500,000+  Free     0   
U Launcher Lite – FREE Live Cool Themes, Hide Apps   5,000,000+  Free     0   
Sketch - Draw & Paint                               50,000,000+  Free     0   
Pixel Draw - Number Art Coloring Book                  100,000+  Free     0   
...                                                         ...   ...   ...   
Sya9a Maroc - FR                                         5,000+  Free     0   
Fr. Mike Schmitz Audio Teachings                           100+  Free     0   
Parkinson Exercices FR                                   1,000+  Free     0   
The SCP Foundation DB fr nn5n                            1,000+  Free     0   
iHoroscope - 2018 Daily Horoscope & Astrology       10,000,000+  Free     0   

                                                   Content Rating  \
App                                                                 
Photo Editor & Candy Camera & Grid & ScrapBook 

In [7]:
# loc et iloc 
test = df_google_apps_index.loc["Coloring book moana", "Size"]
print(test)


App
Coloring book moana    14M
Coloring book moana    14M
Name: Size, dtype: object


In [8]:
df_google_apps_index.iloc[1, 3]

'14M'

In [9]:
df_google_apps_index.iloc[0:4, :5]

Category  Rating  \
App                                                                          
Photo Editor & Candy Camera & Grid & ScrapBook      ART_AND_DESIGN     4.1   
Coloring book moana                                 ART_AND_DESIGN     3.9   
U Launcher Lite – FREE Live Cool Themes, Hide Apps  ART_AND_DESIGN     4.7   
Sketch - Draw & Paint                               ART_AND_DESIGN     4.5   

                                                   Reviews  Size     Installs  
App                                                                            
Photo Editor & Candy Camera & Grid & ScrapBook         159   19M      10,000+  
Coloring book moana                                    967   14M     500,000+  
U Launcher Lite – FREE Live Cool Themes, Hide Apps   87510  8.7M   5,000,000+  
Sketch - Draw & Paint                               215644   25M  50,000,000+

In [10]:
#ajouter une colonne 
category = df_google_apps_index["Category"]
df_google_apps_index["Category_bis"] = category
df_google_apps_index

Category  \
App                                                                       
Photo Editor & Candy Camera & Grid & ScrapBook           ART_AND_DESIGN   
Coloring book moana                                      ART_AND_DESIGN   
U Launcher Lite – FREE Live Cool Themes, Hide Apps       ART_AND_DESIGN   
Sketch - Draw & Paint                                    ART_AND_DESIGN   
Pixel Draw - Number Art Coloring Book                    ART_AND_DESIGN   
...                                                                 ...   
Sya9a Maroc - FR                                                 FAMILY   
Fr. Mike Schmitz Audio Teachings                                 FAMILY   
Parkinson Exercices FR                                          MEDICAL   
The SCP Foundation DB fr nn5n                       BOOKS_AND_REFERENCE   
iHoroscope - 2018 Daily Horoscope & Astrology                 LIFESTYLE   

                                                    Rating Reviews  \
App                                                                  
Photo Editor & Candy Camera & Grid & ScrapBook         4.1     159   
Coloring book moana                                    3.9     967   
U Launcher Lite – FREE Live Cool Themes, Hide Apps     4.7   87510   
Sketch - Draw & Paint                                  4.5  215644   
Pixel Draw - Number Art Coloring Book                  4.3     967   
...                                                    ...     ...   
Sya9a Maroc - FR                                       4.5      38   
Fr. Mike Schmitz Audio Teachings                       5.0       4   
Parkinson Exercices FR                                 NaN       3   
The SCP Foundation DB fr nn5n                          4.5     114   
iHoroscope - 2018 Daily Horoscope & Astrology          4.5  398307   

                                                                  Size  \
App                                                                      
Photo Editor & Candy Camera & Grid & ScrapBook                     19M   
Coloring book moana                                                14M   
U Launcher Lite – FREE Live Cool Themes, Hide Apps                8.7M   
Sketch - Draw & Paint                                              25M   
Pixel Draw - Number Art Coloring Book                             2.8M   
...                                                                ...   
Sya9a Maroc - FR                                                   53M   
Fr. Mike Schmitz Audio Teachings                                  3.6M   
Parkinson Exercices FR                                            9.5M   
The SCP Foundation DB fr nn5n                       Varies with device   
iHoroscope - 2018 Daily Horoscope & Astrology                      19M   

                                                       Installs  Type Price  \
App                                                                           
Photo Editor & Candy Camera & Grid & ScrapBook          10,000+  Free     0   
Coloring book moana                                    500,000+  Free     0   
U Launcher Lite – FREE Live Cool Themes, Hide Apps   5,000,000+  Free     0   
Sketch - Draw & Paint                               50,000,000+  Free     0   
Pixel Draw - Number Art Coloring Book                  100,000+  Free     0   
...                                                         ...   ...   ...   
Sya9a Maroc - FR                                         5,000+  Free     0   
Fr. Mike Schmitz Audio Teachings                           100+  Free     0   
Parkinson Exercices FR                                   1,000+  Free     0   
The SCP Foundation DB fr nn5n                            1,000+  Free     0   
iHoroscope - 2018 Daily Horoscope & Astrology       10,000,000+  Free     0   

                                                   Content Rating  \
App                                                                 
Photo Editor & Candy Camera & Grid & ScrapBook 

In [11]:
# Remove a column
df_google_apps_index.drop(["Category_bis","Android Ver"], axis=1)

Category  \
App                                                                       
Photo Editor & Candy Camera & Grid & ScrapBook           ART_AND_DESIGN   
Coloring book moana                                      ART_AND_DESIGN   
U Launcher Lite – FREE Live Cool Themes, Hide Apps       ART_AND_DESIGN   
Sketch - Draw & Paint                                    ART_AND_DESIGN   
Pixel Draw - Number Art Coloring Book                    ART_AND_DESIGN   
...                                                                 ...   
Sya9a Maroc - FR                                                 FAMILY   
Fr. Mike Schmitz Audio Teachings                                 FAMILY   
Parkinson Exercices FR                                          MEDICAL   
The SCP Foundation DB fr nn5n                       BOOKS_AND_REFERENCE   
iHoroscope - 2018 Daily Horoscope & Astrology                 LIFESTYLE   

                                                    Rating Reviews  \
App                                                                  
Photo Editor & Candy Camera & Grid & ScrapBook         4.1     159   
Coloring book moana                                    3.9     967   
U Launcher Lite – FREE Live Cool Themes, Hide Apps     4.7   87510   
Sketch - Draw & Paint                                  4.5  215644   
Pixel Draw - Number Art Coloring Book                  4.3     967   
...                                                    ...     ...   
Sya9a Maroc - FR                                       4.5      38   
Fr. Mike Schmitz Audio Teachings                       5.0       4   
Parkinson Exercices FR                                 NaN       3   
The SCP Foundation DB fr nn5n                          4.5     114   
iHoroscope - 2018 Daily Horoscope & Astrology          4.5  398307   

                                                                  Size  \
App                                                                      
Photo Editor & Candy Camera & Grid & ScrapBook                     19M   
Coloring book moana                                                14M   
U Launcher Lite – FREE Live Cool Themes, Hide Apps                8.7M   
Sketch - Draw & Paint                                              25M   
Pixel Draw - Number Art Coloring Book                             2.8M   
...                                                                ...   
Sya9a Maroc - FR                                                   53M   
Fr. Mike Schmitz Audio Teachings                                  3.6M   
Parkinson Exercices FR                                            9.5M   
The SCP Foundation DB fr nn5n                       Varies with device   
iHoroscope - 2018 Daily Horoscope & Astrology                      19M   

                                                       Installs  Type Price  \
App                                                                           
Photo Editor & Candy Camera & Grid & ScrapBook          10,000+  Free     0   
Coloring book moana                                    500,000+  Free     0   
U Launcher Lite – FREE Live Cool Themes, Hide Apps   5,000,000+  Free     0   
Sketch - Draw & Paint                               50,000,000+  Free     0   
Pixel Draw - Number Art Coloring Book                  100,000+  Free     0   
...                                                         ...   ...   ...   
Sya9a Maroc - FR                                         5,000+  Free     0   
Fr. Mike Schmitz Audio Teachings                           100+  Free     0   
Parkinson Exercices FR                                   1,000+  Free     0   
The SCP Foundation DB fr nn5n                            1,000+  Free     0   
iHoroscope - 2018 Daily Horoscope & Astrology       10,000,000+  Free     0   

                                                   Content Rating  \
App                                                                 
Photo Editor & Candy Camera & Grid & ScrapBook 

### <a id='toc1_2_1_'></a>[Remove null values in dataframe](#toc0_)

In [12]:
# count null in dataframe df_google_apps
df_google_apps.isnull().sum()

# dropo all rows with null values
df_google_apps_no_NaN = df_google_apps.dropna()
df_google_apps_no_NaN.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

## <a id='toc1_3_'></a>[Sort dataframe](#toc0_)

In [13]:
df_google_apps_no_NaN.sort_values(by='Rating',ascending=False)

App            Category  \
1038                           Mindvalley U Tallinn 2018              EVENTS   
9517                                             Ek Vote        PRODUCTIVITY   
9427                                             ei Calc               TOOLS   
7367                       Startupticker.ch News, Events  NEWS_AND_MAGAZINES   
9444   Kolkata News:Anandbazar Patrika,ei samay&AllRa...  NEWS_AND_MAGAZINES   
...                                                  ...                 ...   
7427                                      CJ DVD Rentals       COMMUNICATION   
10591   Lottery Ticket Checker - Florida Results & Lotto               TOOLS   
7383                                      Thistletown CI        PRODUCTIVITY   
7144                                       CB Mobile Biz             FINANCE   
625                              House party - live chat              DATING   

       Rating Reviews  Size Installs  Type Price Content Rating  \
1038      5.0       1   21M     100+  Free     0       Everyone   
9517      5.0      43  6.2M     500+  Free     0       Everyone   
9427      5.0       2   19M      10+  Free     0       Everyone   
7367      5.0       4   10M     100+  Free     0       Everyone   
9444      5.0      10  5.0M     100+  Free     0       Everyone   
...       ...     ...   ...      ...   ...   ...            ...   
7427      1.0       5   13M     100+  Free     0       Everyone   
10591     1.0       3   41M     500+  Free     0       Everyone   
7383      1.0       1  6.6M     100+  Free     0       Everyone   
7144      1.0       3  8.4M     500+  Free     0       Everyone   
625       1.0       1  9.2M      10+  Free     0     Mature 17+   

                 Genres       Last Updated Current Ver   Android Ver  
1038             Events       July 3, 2018       1.0.5    4.4 and up  
9517       Productivity   November 7, 2017         1.1  4.0.3 and up  
9427              Tools   October 12, 2015       1.2.2    2.3 and up  
7367   News & Magazines      July 23, 2018       2.0.0    4.4 and up  
9444   News & Magazines      July 14, 2018         1.0  4.0.3 and up  
...                 ...                ...         ...           ...  
7427      Communication    October 6, 2017         1.0    4.1 and up  
10591             Tools  December 12, 2017         1.0    4.2 and up  
7383       Productivity     March 15, 2018        41.9    4.1 and up  
7144            Finance  February 22, 2016    4.4.1255    4.0 and up  
625              Dating      July 31, 2018        3.52  4.0.3 and up  

[9360 rows x 13 columns]

## <a id='toc1_4_'></a>[Conversion data in dataframe](#toc0_)

In [14]:
# Check type of all dataframe column
df_google_apps_no_NaN.dtypes

df_google_apps_no_NaN.describe(include="all")

App Category       Rating Reviews                Size    Installs  \
count     9360     9360  9360.000000    9360                9360        9360   
unique    8190       33          NaN    5990                 413          19   
top     ROBLOX   FAMILY          NaN       2  Varies with device  1,000,000+   
freq         9     1746          NaN      83                1637        1576   
mean       NaN      NaN     4.191838     NaN                 NaN         NaN   
std        NaN      NaN     0.515263     NaN                 NaN         NaN   
min        NaN      NaN     1.000000     NaN                 NaN         NaN   
25%        NaN      NaN     4.000000     NaN                 NaN         NaN   
50%        NaN      NaN     4.300000     NaN                 NaN         NaN   
75%        NaN      NaN     4.500000     NaN                 NaN         NaN   
max        NaN      NaN     5.000000     NaN                 NaN         NaN   

        Type Price Content Rating Genres    Last Updated         Current Ver  \
count   9360  9360           9360   9360            9360                9360   
unique     2    73              6    115            1299                2638   
top     Free     0       Everyone  Tools  August 3, 2018  Varies with device   
freq    8715  8715           7414    732             319                1415   
mean     NaN   NaN            NaN    NaN             NaN                 NaN   
std      NaN   NaN            NaN    NaN             NaN                 NaN   
min      NaN   NaN            NaN    NaN             NaN                 NaN   
25%      NaN   NaN            NaN    NaN             NaN                 NaN   
50%      NaN   NaN            NaN    NaN             NaN                 NaN   
75%      NaN   NaN            NaN    NaN             NaN                 NaN   
max      NaN   NaN            NaN    NaN             NaN                 NaN   

       Android Ver  
count         9360  
unique          31  
top     4.1 and up  
freq          2059  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN

In [15]:
# Replace values in a column
df_google_apps_no_NaN['Installs_bis'] = df_google_apps_no_NaN['Installs'].str.replace('+','').str.replace(',','').astype(int)
df_google_apps_no_NaN
df_google_apps_no_NaN['Reviews'] = df_google_apps_no_NaN['Reviews'].astype(int)
df_google_apps_no_NaN

/var/folders/8t/_zpznyq52g12p_gphjl4pq8c0000gn/T/ipykernel_79903/556545554.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_google_apps_no_NaN['Installs_bis'] = df_google_apps_no_NaN['Installs'].str.replace('+','').str.replace(',','').astype(int)
/var/folders/8t/_zpznyq52g12p_gphjl4pq8c0000gn/T/ipykernel_79903/556545554.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_google_apps_no_NaN['Reviews'] = df_google_apps_no_NaN['Reviews'].astype(int)


App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10834                                      FR Calculator               FAMILY   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating  Reviews                Size     Installs  Type Price  \
0         4.1      159                 19M      10,000+  Free     0   
1         3.9      967                 14M     500,000+  Free     0   
2         4.7    87510                8.7M   5,000,000+  Free     0   
3         4.5   215644                 25M  50,000,000+  Free     0   
4         4.3      967                2.8M     100,000+  Free     0   
...       ...      ...                 ...          ...   ...   ...   
10834     4.0        7                2.6M         500+  Free     0   
10836     4.5       38                 53M       5,000+  Free     0   
10837     5.0        4                3.6M         100+  Free     0   
10839     4.5      114  Varies with device       1,000+  Free     0   
10840     4.5   398307                 19M  10,000,000+  Free     0   

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018   
1           Everyone  Art & Design;Pretend Play  January 15, 2018   
2           Everyone               Art & Design    August 1, 2018   
3               Teen               Art & Design      June 8, 2018   
4           Everyone    Art & Design;Creativity     June 20, 2018   
...              ...                        ...               ...   
10834       Everyone                  Education     June 18, 2017   
10836       Everyone                  Education     July 25, 2017   
10837       Everyone                  Education      July 6, 2018   
10839     Mature 17+          Books & Reference  January 19, 2015   
10840       Everyone                  Lifestyle     July 25, 2018   

              Current Ver         Android Ver  Installs_bis  
0                   1.0.0        4.0.3 and up         10000  
1                   2.0.0        4.0.3 and up        500000  
2                   1.2.4        4.0.3 and up       5000000  
3      Varies with device          4.2 and up      50000000  
4                     1.1          4.4 and up        100000  
...                   ...                 ...           ...  
10834               1.0.0          4.1 and up           500  
10836                1.48          4.1 and up          5000  
10837                 1.0          4.1 and up           100  
10839  Varies with device  Varies with device          1000  
10840  Varies with device  Varies with device      10000000  

[9360 rows x 14 columns]

## <a id='toc1_5_'></a>[Filter in dataframe](#toc0_)

In [16]:
# Get only df with the rating is higher than 4.5
df_google_apps_no_NaN.loc[df_google_apps_no_NaN["Rating"] > 4.5,:]
#df_google_apps_no_NaN_supp = df_google_apps_no_NaN[df_google_apps_no_NaN.loc["Rating"] > 4.5:]

App             Category  \
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
9                          Kids Paint Free - Drawing Fun       ART_AND_DESIGN   
13                                 Mandala Coloring Book       ART_AND_DESIGN   
16          Photo Designer - Write your name with shapes       ART_AND_DESIGN   
19                                          ibis Paint X       ART_AND_DESIGN   
...                                                  ...                  ...   
10810                                  Fr Lupupa Sermons             BUSINESS   
10820                                    Fr. Daoud Lamei               FAMILY   
10829                     Bulgarian French Dictionary Fr  BOOKS_AND_REFERENCE   
10833                                        Chemin (fr)  BOOKS_AND_REFERENCE   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   

       Rating  Reviews  Size     Installs  Type Price Content Rating  \
2         4.7    87510  8.7M   5,000,000+  Free     0       Everyone   
9         4.7      121  3.1M      10,000+  Free     0       Everyone   
13        4.6     4326   21M     100,000+  Free     0       Everyone   
16        4.7     3632  5.5M     500,000+  Free     0       Everyone   
19        4.6   224399   31M  10,000,000+  Free     0       Everyone   
...       ...      ...   ...          ...   ...   ...            ...   
10810     4.8       19   21M         100+  Free     0       Everyone   
10820     5.0       22  8.6M       1,000+  Free     0           Teen   
10829     4.6      603  7.4M      10,000+  Free     0       Everyone   
10833     4.8       44  619k       1,000+  Free     0       Everyone   
10837     5.0        4  3.6M         100+  Free     0       Everyone   

                        Genres    Last Updated Current Ver   Android Ver  \
2                 Art & Design  August 1, 2018       1.2.4  4.0.3 and up   
9      Art & Design;Creativity    July 3, 2018         2.8  4.0.3 and up   
13                Art & Design   June 26, 2018       1.0.4    4.4 and up   
16                Art & Design   July 31, 2018         3.1    4.1 and up   
19                Art & Design   July 30, 2018       5.5.4    4.1 and up   
...                        ...             ...         ...           ...   
10810                 Business   June 12, 2018         1.0    4.4 and up   
10820                Education   June 27, 2018       3.8.0    4.1 and up   
10829        Books & Reference   June 19, 2016        2.96    4.1 and up   
10833        Books & Reference  March 23, 2014         0.8    2.2 and up   
10837                Education    July 6, 2018         1.0    4.1 and up   

       Installs_bis  
2           5000000  
9             10000  
13           100000  
16           500000  
19         10000000  
...             ...  
10810           100  
10820          1000  
10829         10000  
10833          1000  
10837           100  

[1917 rows x 14 columns]

In [17]:
# filter applications in Business category
df_google_apps_no_NaN.loc[df_google_apps_no_NaN['Category']=='BUSINESS',:]

App  Category  Rating  \
187                         Visual Voicemail by MetroPCS  BUSINESS     4.1   
188                                    Indeed Job Search  BUSINESS     4.3   
189                                          Uber Driver  BUSINESS     4.4   
190                                 ADP Mobile Solutions  BUSINESS     4.3   
191                               Snag - Jobs Hiring Now  BUSINESS     4.3   
...                                                  ...       ...     ...   
10624                              Employ Florida Mobile  BUSINESS     2.9   
10659                                                 FN  BUSINESS     5.0   
10706  Neon Blue Gaming Wallpaper&Theme fo Lenovo K8 ...  BUSINESS     4.6   
10754                                     SCM FPS Status  BUSINESS     4.2   
10810                                  Fr Lupupa Sermons  BUSINESS     4.8   

       Reviews                Size     Installs  Type Price Content Rating  \
187      16129  Varies with device  10,000,000+  Free     0       Everyone   
188     674730  Varies with device  50,000,000+  Free     0       Everyone   
189    1254730  Varies with device  10,000,000+  Free     0       Everyone   
190      85185                 29M   5,000,000+  Free     0       Everyone   
191      32584  Varies with device   1,000,000+  Free     0       Everyone   
...        ...                 ...          ...   ...   ...            ...   
10624       97                9.9M      10,000+  Free     0       Everyone   
10659       14                3.3M          50+  Free     0       Everyone   
10706        7                2.0M         500+  Free     0       Everyone   
10754      123                3.3M      10,000+  Free     0       Everyone   
10810       19                 21M         100+  Free     0       Everyone   

         Genres      Last Updated         Current Ver         Android Ver  \
187    Business     July 30, 2018  Varies with device  Varies with device   
188    Business      May 21, 2018  Varies with device  Varies with device   
189    Business    August 3, 2018  Varies with device  Varies with device   
190    Business     July 17, 2018               3.4.2          5.0 and up   
191    Business       May 4, 2018  Varies with device  Varies with device   
...         ...               ...                 ...                 ...   
10624  Business     June 13, 2018               4.5.9        4.0.3 and up   
10659  Business  February 1, 2018                 1.0          4.0 and up   
10706  Business   August 24, 2017               1.0.0        2.3.3 and up   
10754  Business    April 28, 2018                 3.5          2.3 and up   
10810  Business     June 12, 2018                 1.0          4.4 and up   

       Installs_bis  
187        10000000  
188        50000000  
189        10000000  
190         5000000  
191         1000000  
...             ...  
10624         10000  
10659            50  
10706           500  
10754         10000  
10810           100  

[303 rows x 14 columns]

In [18]:
# filter applications in Business category who has more than 4.5 rating
df_google_apps_no_NaN.loc[(df_google_apps_no_NaN['Category'] == 'BUSINESS') & (df_google_apps_no_NaN["Rating"] > 4.5), :]

App  Category  Rating  \
196                           Job Search by ZipRecruiter  BUSINESS     4.8   
206                                         Call Blocker  BUSINESS     4.6   
208                           Square Point of Sale - POS  BUSINESS     4.6   
221                                        Myanmar 2D/3D  BUSINESS     4.6   
224                       ATI Cargoes and Transportation  BUSINESS     4.7   
...                                                  ...       ...     ...   
10412                                             FH App  BUSINESS     4.9   
10529                                 FK CLASSIC FOR YOU  BUSINESS     5.0   
10659                                                 FN  BUSINESS     5.0   
10706  Neon Blue Gaming Wallpaper&Theme fo Lenovo K8 ...  BUSINESS     4.6   
10810                                  Fr Lupupa Sermons  BUSINESS     4.8   

       Reviews                Size    Installs  Type Price Content Rating  \
196     148945                 25M  1,000,000+  Free     0       Everyone   
206     188841                3.2M  5,000,000+  Free     0       Everyone   
208      95912  Varies with device  5,000,000+  Free     0       Everyone   
221        822                3.1M    100,000+  Free     0       Everyone   
224       4162                7.5M    100,000+  Free     0       Everyone   
...        ...                 ...         ...   ...   ...            ...   
10412       27                6.0M        100+  Free     0       Everyone   
10529        1                3.5M         10+  Free     0       Everyone   
10659       14                3.3M         50+  Free     0       Everyone   
10706        7                2.0M        500+  Free     0       Everyone   
10810       19                 21M        100+  Free     0       Everyone   

         Genres       Last Updated         Current Ver         Android Ver  \
196    Business      July 19, 2018               5.2.8          5.0 and up   
206    Business      June 21, 2018              1.1.13          4.0 and up   
208    Business      July 30, 2018  Varies with device  Varies with device   
221    Business       June 8, 2018                 1.5        4.0.3 and up   
224    Business      July 24, 2018               0.9.4        4.0.3 and up   
...         ...                ...                 ...                 ...   
10412  Business      July 26, 2018              1.0.90          4.0 and up   
10529  Business  February 20, 2018               1.1.0          4.0 and up   
10659  Business   February 1, 2018                 1.0          4.0 and up   
10706  Business    August 24, 2017               1.0.0        2.3.3 and up   
10810  Business      June 12, 2018                 1.0          4.4 and up   

       Installs_bis  
196         1000000  
206         5000000  
208         5000000  
221          100000  
224          100000  
...             ...  
10412           100  
10529            10  
10659            50  
10706           500  
10810           100  

[66 rows x 14 columns]

## <a id='toc1_6_'></a>[Group a column in dataframe](#toc0_)

In [19]:
# group by Price
df_google_apps_no_NaN['Price bis']= df_google_apps_no_NaN['Price'].str.replace('$','').astype(float)
df_google_apps_no_NaN.groupby(['Category','Genres']).describe()



/var/folders/8t/_zpznyq52g12p_gphjl4pq8c0000gn/T/ipykernel_79903/4105241091.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_google_apps_no_NaN['Price bis']= df_google_apps_no_NaN['Price'].str.replace('$','').astype(float)


Rating            \
                                                         count      mean   
Category          Genres                                                   
ART_AND_DESIGN    Art & Design                            55.0  4.380000   
                  Art & Design;Creativity                  5.0  4.440000   
                  Art & Design;Pretend Play                1.0  3.900000   
AUTO_AND_VEHICLES Auto & Vehicles                         73.0  4.190411   
BEAUTY            Beauty                                  42.0  4.278571   
...                                                        ...       ...   
TRAVEL_AND_LOCAL  Travel & Local;Action & Adventure        1.0  4.100000   
VIDEO_PLAYERS     Video Players & Editors                158.0  4.063924   
                  Video Players & Editors;Creativity       1.0  4.100000   
                  Video Players & Editors;Music & Video    1.0  4.000000   
WEATHER           Weather                                 75.0  4.244000   

                                                                              \
                                                              std  min   25%   
Category          Genres                                                       
ART_AND_DESIGN    Art & Design                           0.321685  3.4  4.15   
                  Art & Design;Creativity                0.397492  3.8  4.30   
                  Art & Design;Pretend Play                   NaN  3.9  3.90   
AUTO_AND_VEHICLES Auto & Vehicles                        0.543692  2.1  4.00   
BEAUTY            Beauty                                 0.362603  3.1  4.00   
...                                                           ...  ...   ...   
TRAVEL_AND_LOCAL  Travel & Local;Action & Adventure           NaN  4.1  4.10   
VIDEO_PLAYERS     Video Players & Editors                0.554566  1.8  3.80   
                  Video Players & Editors;Creativity          NaN  4.1  4.10   
                  Video Players & Editors;Music & Video       NaN  4.0  4.00   
WEATHER           Weather                                0.331353  3.3  4.05   

                                                                          \
                                                         50%    75%  max   
Category          Genres                                                   
ART_AND_DESIGN    Art & Design                           4.4  4.700  5.0   
                  Art & Design;Creativity                4.7  4.700  4.7   
                  Art & Design;Pretend Play              3.9  3.900  3.9   
AUTO_AND_VEHICLES Auto & Vehicles                        4.3  4.600  4.9   
BEAUTY            Beauty                                 4.3  4.575  4.9   
...                                                      ...    ...  ...   
TRAVEL_AND_LOCAL  Travel & Local;Action & Adventure      4.1  4.100  4.1   
VIDEO_PLAYERS     Video Players & Editors                4.2  4.400  4.9   
                  Video Players & Editors;Creativity     4.1  4.100  4.1   
                  Video Players & Editors;Music & Video  4.0  4.000  4.0   
WEATHER           Weather                                4.3  4.500  4.8   

                                                        Reviews  \
                                                          count   
Category          Genres                                          
ART_AND_DESIGN    Art & Design                             55.0   
                  Art & Design;Creativity                   5.0   
                  Art & Design;Pretend Play                 1.0   
AUTO_AND_VEHICLES Auto & Vehicles                          73.0   
BEAUTY            Beauty                                   42.0   
...                                                         ...   
TRAVEL_AND_LOCAL  Travel & Local;Action & Adventure         1.0   
VIDEO_PLAYERS     Video Players & Editors                 158.0   
                  Video Players & Editors;Creativity        1.0   
 

# <a id='toc2_'></a>[Exercice :](#toc0_)
Objectif : Etudier le marché Android via le Google Play Store


### <a id='toc2_1_1_'></a>[Quels sont les noms, les catégories et les genres des applications les plus installées sur Google Play ?](#toc0_)

In [20]:
# les nom d'application les plus installé sur Google Play
print(df_google_apps['Installs'].unique())

# Remove all the free apps in df_.._clean
df_google_apps_clean = df_google_apps[df_google_apps['Installs'] != 'Free']

# Transform nbr app from string to number
df_google_apps_clean['Installs_clean'] = df_google_apps_clean['Installs'].str.replace('+','', regex=False).str.replace(',', '', regex=False).astype(int)

max_install = df_google_apps_clean['Installs_clean'].max()
print(f"max app = {max_install}")
df_google_apps_max_install = df_google_apps_clean[df_google_apps_clean['Installs_clean'] == max_install]

#.sort_values(by='Installs_clean', ascending=False)

df_google_apps_max_install

['10,000+' '500,000+' '5,000,000+' '50,000,000+' '100,000+' '50,000+'
 '1,000,000+' '10,000,000+' '5,000+' '100,000,000+' '1,000,000,000+'
 '1,000+' '500,000,000+' '50+' '100+' '500+' '10+' '1+' '5+' '0+' '0'
 'Free']
max app = 1000000000


/var/folders/8t/_zpznyq52g12p_gphjl4pq8c0000gn/T/ipykernel_79903/2919299908.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_google_apps_clean['Installs_clean'] = df_google_apps_clean['Installs'].str.replace('+','', regex=False).str.replace(',', '', regex=False).astype(int)


App             Category  Rating  \
152                          Google Play Books  BOOKS_AND_REFERENCE     3.9   
335   Messenger – Text and Video Chat for Free        COMMUNICATION     4.0   
336                         WhatsApp Messenger        COMMUNICATION     4.4   
338               Google Chrome: Fast & Secure        COMMUNICATION     4.3   
340                                      Gmail        COMMUNICATION     4.3   
341                                   Hangouts        COMMUNICATION     4.0   
381                         WhatsApp Messenger        COMMUNICATION     4.4   
382   Messenger – Text and Video Chat for Free        COMMUNICATION     4.0   
386                                   Hangouts        COMMUNICATION     4.0   
391              Skype - free IM & video calls        COMMUNICATION     4.1   
411               Google Chrome: Fast & Secure        COMMUNICATION     4.3   
451                                      Gmail        COMMUNICATION     4.3   
464                                   Hangouts        COMMUNICATION     4.0   
468              Skype - free IM & video calls        COMMUNICATION     4.1   
865                          Google Play Games        ENTERTAINMENT     4.3   
1654                            Subway Surfers                 GAME     4.5   
1700                            Subway Surfers                 GAME     4.5   
1750                            Subway Surfers                 GAME     4.5   
1872                            Subway Surfers                 GAME     4.5   
1917                            Subway Surfers                 GAME     4.5   
2544                                  Facebook               SOCIAL     4.1   
2545                                 Instagram               SOCIAL     4.5   
2554                                   Google+               SOCIAL     4.2   
2604                                 Instagram               SOCIAL     4.5   
2611                                 Instagram               SOCIAL     4.5   
2808                             Google Photos          PHOTOGRAPHY     4.5   
2853                             Google Photos          PHOTOGRAPHY     4.5   
2884                             Google Photos          PHOTOGRAPHY     4.5   
3117                 Maps - Navigate & Explore     TRAVEL_AND_LOCAL     4.3   
3127                        Google Street View     TRAVEL_AND_LOCAL     4.2   
3223                 Maps - Navigate & Explore     TRAVEL_AND_LOCAL     4.3   
3232                        Google Street View     TRAVEL_AND_LOCAL     4.2   
3234                                    Google                TOOLS     4.4   
3454                              Google Drive         PRODUCTIVITY     4.4   
3523                              Google Drive         PRODUCTIVITY     4.4   
3565                              Google Drive         PRODUCTIVITY     4.4   
3665                                   YouTube        VIDEO_PLAYERS     4.3   
3687                   Google Play Movies & TV        VIDEO_PLAYERS     3.7   
3736                               Google News   NEWS_AND_MAGAZINES     3.9   
3765                               Google News   NEWS_AND_MAGAZINES     3.9   
3816                               Google News   NEWS_AND_MAGAZINES     3.9   
3896                            Subway Surfers                 GAME     4.5   
3904                        WhatsApp Messenger        COMMUNICATION     4.4   
3909                                 Instagram               SOCIAL     4.5   
3928                                   YouTube        VIDEO_PLAYERS     4.3   
3943                                  Facebook               SOCIAL     4.1   
3996              Google Chrome: Fast & Secure        COMMUNICATION     4.3   
4096                                     Gmail        COMMUNICATION     4.3   
4098                 Maps - Navigate & Explore     TRAVEL_AND_LOCAL     4.3   
4104  Messenger – Text and Video Chat for Free        COMMUNICATION     4.0   
4144          

### <a id='toc2_1_2_'></a>[Quel est le plus grand nombre de Reviews ? (avis) Quel est le nom et la note globale de l’application concernée ?](#toc0_)

In [21]:
df_google_apps_reviews = df_google_apps.dropna()

df_google_apps_reviews['Reviews'] = df_google_apps_reviews['Reviews'].astype(int)

max_reviews = df_google_apps_reviews['Reviews'].max()

df_google_apps_reviews[df_google_apps_reviews['Reviews'] == max_reviews].loc[:,['App','Rating']]


/var/folders/8t/_zpznyq52g12p_gphjl4pq8c0000gn/T/ipykernel_79903/1870766918.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_google_apps_reviews['Reviews'] = df_google_apps_reviews['Reviews'].astype(int)


App  Rating
2544  Facebook     4.1

### Afficher les colonnes 2,5,6 et les lignes 3 à 16 du dataframe


In [22]:
df_google_apps.iloc[2:16,[1,4,5]]

Category  Size     Installs
2   ART_AND_DESIGN  8.7M   5,000,000+
3   ART_AND_DESIGN   25M  50,000,000+
4   ART_AND_DESIGN  2.8M     100,000+
5   ART_AND_DESIGN  5.6M      50,000+
6   ART_AND_DESIGN   19M      50,000+
7   ART_AND_DESIGN   29M   1,000,000+
8   ART_AND_DESIGN   33M   1,000,000+
9   ART_AND_DESIGN  3.1M      10,000+
10  ART_AND_DESIGN   28M   1,000,000+
11  ART_AND_DESIGN   12M   1,000,000+
12  ART_AND_DESIGN   20M  10,000,000+
13  ART_AND_DESIGN   21M     100,000+
14  ART_AND_DESIGN   37M     100,000+
15  ART_AND_DESIGN  2.7M       5,000+

#### Combien y a-t-il d’applications ouvertes aux personnes de tous âge ? (Everyone)


In [23]:
df_google_apps[df_google_apps['Content Rating'] == 'Everyone'].shape

(8714, 13)

### Dans quelle catégorie y a-t-il le plus d’applications ?


In [28]:
df_google_apps_clean.loc[:,['Category','Installs_clean']].groupby(['Category']).sum()

Installs_clean
Category                           
ART_AND_DESIGN            124338100
AUTO_AND_VEHICLES          53130211
BEAUTY                     27197050
BOOKS_AND_REFERENCE      1921469576
BUSINESS                 1001914865
COMICS                     56086150
COMMUNICATION           32647276251
DATING                    264310807
EDUCATION                 871452000
ENTERTAINMENT            2869160000
EVENTS                     15973161
FAMILY                  10258263505
FINANCE                   876648734
FOOD_AND_DRINK            273898751
GAME                    35086024415
HEALTH_AND_FITNESS       1583072512
HOUSE_AND_HOME            168712461
LIBRARIES_AND_DEMO         62995910
LIFESTYLE                 537643539
MAPS_AND_NAVIGATION       724281890
MEDICAL                    53257437
NEWS_AND_MAGAZINES       7496317760
PARENTING                  31521110
PERSONALIZATION          2325494782
PHOTOGRAPHY             10088247655
PRODUCTIVITY            14176091369
SHOPPING                 3247848785
SOCIAL                  14069867902
SPORTS                   1751174498
TOOLS                   11452771915
TRAVEL_AND_LOCAL         6868887146
VIDEO_PLAYERS            6222002720
WEATHER                   426100520

### Quelle est l’application vendue la plus chère ?