# Tutorial - Udemy - Programmer en Python pour la Data Science de A à Z
**Objective : Hands one in Numpy, Pandas and Matplotlib libraries**

## 1. Exploring Series

In [2]:
import pandas as pd
import numpy as np

In [3]:
serie = pd.Series([17, 24, 32, 40, 51,1])
print(serie)

# replace index serie with names
serie.index = ['Fred', 'beatrice', 'carole', 'dédé', 'egueune', 'fabrice']
print(serie)
serie.describe()

0    17
1    24
2    32
3    40
4    51
5     1
dtype: int64
Fred        17
beatrice    24
carole      32
dédé        40
egueune     51
fabrice      1
dtype: int64


count     6.000000
mean     27.500000
std      17.626684
min       1.000000
25%      18.750000
50%      28.000000
75%      38.000000
max      51.000000
dtype: float64

In [4]:
# Read the csv file by using nmumpy 
houses = np.genfromtxt('Houses.csv', delimiter=',', dtype=int, encoding='utf-8')
print(houses)

[[212000   4148  25264]
 [230000   2501  11891]
 [339000   4374  25351]
 [289000   2398  22215]
 [160000   2536   9234]
 [ 85000   2368  13329]
 [ 85000   1264   8407]
 [145000   1572  12588]
 [164000   2375  16204]
 [123500   1161   9626]
 [180000   1542   8755]
 [159500   1464  14636]
 [156000   2240  21780]
 [146500   1269  11250]
 [101500    924   7361]
 [109800    768  10497]
 [182000   1320  15768]
 [110000   1845  12153]
 [125000   1274  13634]
 [ 80000   1905  10890]]


In [5]:
df_houses = pd.DataFrame(houses, columns=['Prix', 'Taille de la maison', 'Surface'])
df_houses

Prix  Taille de la maison  Surface
0   212000                 4148    25264
1   230000                 2501    11891
2   339000                 4374    25351
3   289000                 2398    22215
4   160000                 2536     9234
5    85000                 2368    13329
6    85000                 1264     8407
7   145000                 1572    12588
8   164000                 2375    16204
9   123500                 1161     9626
10  180000                 1542     8755
11  159500                 1464    14636
12  156000                 2240    21780
13  146500                 1269    11250
14  101500                  924     7361
15  109800                  768    10497
16  182000                 1320    15768
17  110000                 1845    12153
18  125000                 1274    13634
19   80000                 1905    10890

## 2. Exploring Pandas

In [6]:
# Create Dataframe from series
group1 = pd.Series([11, 21, 31, 41, 51], index=['a', 'b', 'c', 'd', 'e'])
group2 = pd.Series([60, 70, 80, 90, 10], index=['alix', 'baa', 'c', 'd', 'edil'])
df_group = pd.DataFrame({'group1': group1, 'group2': group2})
df_group

group1  group2
a       11.0     NaN
alix     NaN    60.0
b       21.0     NaN
baa      NaN    70.0
c       31.0    80.0
d       41.0    90.0
e       51.0     NaN
edil     NaN    10.0

In [19]:
# Read the csv file by using pandas
df_google_apps = pd.read_csv('googleplaystore.csv')
df_google_apps

# Write a csv file
df_google_apps.to_csv('googleplaystore_copy.csv', index=False)

df_google_apps_index = df_google_apps.set_index('App')

df_google_apps_index

Category  \
App                                                                       
Photo Editor & Candy Camera & Grid & ScrapBook           ART_AND_DESIGN   
Coloring book moana                                      ART_AND_DESIGN   
U Launcher Lite – FREE Live Cool Themes, Hide Apps       ART_AND_DESIGN   
Sketch - Draw & Paint                                    ART_AND_DESIGN   
Pixel Draw - Number Art Coloring Book                    ART_AND_DESIGN   
...                                                                 ...   
Sya9a Maroc - FR                                                 FAMILY   
Fr. Mike Schmitz Audio Teachings                                 FAMILY   
Parkinson Exercices FR                                          MEDICAL   
The SCP Foundation DB fr nn5n                       BOOKS_AND_REFERENCE   
iHoroscope - 2018 Daily Horoscope & Astrology                 LIFESTYLE   

                                                    Rating Reviews  \
App                                                                  
Photo Editor & Candy Camera & Grid & ScrapBook         4.1     159   
Coloring book moana                                    3.9     967   
U Launcher Lite – FREE Live Cool Themes, Hide Apps     4.7   87510   
Sketch - Draw & Paint                                  4.5  215644   
Pixel Draw - Number Art Coloring Book                  4.3     967   
...                                                    ...     ...   
Sya9a Maroc - FR                                       4.5      38   
Fr. Mike Schmitz Audio Teachings                       5.0       4   
Parkinson Exercices FR                                 NaN       3   
The SCP Foundation DB fr nn5n                          4.5     114   
iHoroscope - 2018 Daily Horoscope & Astrology          4.5  398307   

                                                                  Size  \
App                                                                      
Photo Editor & Candy Camera & Grid & ScrapBook                     19M   
Coloring book moana                                                14M   
U Launcher Lite – FREE Live Cool Themes, Hide Apps                8.7M   
Sketch - Draw & Paint                                              25M   
Pixel Draw - Number Art Coloring Book                             2.8M   
...                                                                ...   
Sya9a Maroc - FR                                                   53M   
Fr. Mike Schmitz Audio Teachings                                  3.6M   
Parkinson Exercices FR                                            9.5M   
The SCP Foundation DB fr nn5n                       Varies with device   
iHoroscope - 2018 Daily Horoscope & Astrology                      19M   

                                                       Installs  Type Price  \
App                                                                           
Photo Editor & Candy Camera & Grid & ScrapBook          10,000+  Free     0   
Coloring book moana                                    500,000+  Free     0   
U Launcher Lite – FREE Live Cool Themes, Hide Apps   5,000,000+  Free     0   
Sketch - Draw & Paint                               50,000,000+  Free     0   
Pixel Draw - Number Art Coloring Book                  100,000+  Free     0   
...                                                         ...   ...   ...   
Sya9a Maroc - FR                                         5,000+  Free     0   
Fr. Mike Schmitz Audio Teachings                           100+  Free     0   
Parkinson Exercices FR                                   1,000+  Free     0   
The SCP Foundation DB fr nn5n                            1,000+  Free     0   
iHoroscope - 2018 Daily Horoscope & Astrology       10,000,000+  Free     0   

                                                   Content Rating  \
App                                                                 
Photo Editor & Candy Camera & Grid & ScrapBook 

In [32]:
# loc et iloc 
test = df_google_apps_index.loc["Coloring book moana", "Size"]
print(test)


App
Coloring book moana    14M
Coloring book moana    14M
Name: Size, dtype: object


In [30]:
df_google_apps_index.iloc[1, 3]

'14M'

In [38]:
df_google_apps_index.iloc[0:4, :5]

Category  Rating  \
App                                                                          
Photo Editor & Candy Camera & Grid & ScrapBook      ART_AND_DESIGN     4.1   
Coloring book moana                                 ART_AND_DESIGN     3.9   
U Launcher Lite – FREE Live Cool Themes, Hide Apps  ART_AND_DESIGN     4.7   
Sketch - Draw & Paint                               ART_AND_DESIGN     4.5   

                                                   Reviews  Size     Installs  
App                                                                            
Photo Editor & Candy Camera & Grid & ScrapBook         159   19M      10,000+  
Coloring book moana                                    967   14M     500,000+  
U Launcher Lite – FREE Live Cool Themes, Hide Apps   87510  8.7M   5,000,000+  
Sketch - Draw & Paint                               215644   25M  50,000,000+

In [42]:
#ajouter une colonne 
category = df_google_apps_index["Category"]
df_google_apps_index["Category_bis"] = category
df_google_apps_index

Category  \
App                                                                       
Photo Editor & Candy Camera & Grid & ScrapBook           ART_AND_DESIGN   
Coloring book moana                                      ART_AND_DESIGN   
U Launcher Lite – FREE Live Cool Themes, Hide Apps       ART_AND_DESIGN   
Sketch - Draw & Paint                                    ART_AND_DESIGN   
Pixel Draw - Number Art Coloring Book                    ART_AND_DESIGN   
...                                                                 ...   
Sya9a Maroc - FR                                                 FAMILY   
Fr. Mike Schmitz Audio Teachings                                 FAMILY   
Parkinson Exercices FR                                          MEDICAL   
The SCP Foundation DB fr nn5n                       BOOKS_AND_REFERENCE   
iHoroscope - 2018 Daily Horoscope & Astrology                 LIFESTYLE   

                                                    Rating Reviews  \
App                                                                  
Photo Editor & Candy Camera & Grid & ScrapBook         4.1     159   
Coloring book moana                                    3.9     967   
U Launcher Lite – FREE Live Cool Themes, Hide Apps     4.7   87510   
Sketch - Draw & Paint                                  4.5  215644   
Pixel Draw - Number Art Coloring Book                  4.3     967   
...                                                    ...     ...   
Sya9a Maroc - FR                                       4.5      38   
Fr. Mike Schmitz Audio Teachings                       5.0       4   
Parkinson Exercices FR                                 NaN       3   
The SCP Foundation DB fr nn5n                          4.5     114   
iHoroscope - 2018 Daily Horoscope & Astrology          4.5  398307   

                                                                  Size  \
App                                                                      
Photo Editor & Candy Camera & Grid & ScrapBook                     19M   
Coloring book moana                                                14M   
U Launcher Lite – FREE Live Cool Themes, Hide Apps                8.7M   
Sketch - Draw & Paint                                              25M   
Pixel Draw - Number Art Coloring Book                             2.8M   
...                                                                ...   
Sya9a Maroc - FR                                                   53M   
Fr. Mike Schmitz Audio Teachings                                  3.6M   
Parkinson Exercices FR                                            9.5M   
The SCP Foundation DB fr nn5n                       Varies with device   
iHoroscope - 2018 Daily Horoscope & Astrology                      19M   

                                                       Installs  Type Price  \
App                                                                           
Photo Editor & Candy Camera & Grid & ScrapBook          10,000+  Free     0   
Coloring book moana                                    500,000+  Free     0   
U Launcher Lite – FREE Live Cool Themes, Hide Apps   5,000,000+  Free     0   
Sketch - Draw & Paint                               50,000,000+  Free     0   
Pixel Draw - Number Art Coloring Book                  100,000+  Free     0   
...                                                         ...   ...   ...   
Sya9a Maroc - FR                                         5,000+  Free     0   
Fr. Mike Schmitz Audio Teachings                           100+  Free     0   
Parkinson Exercices FR                                   1,000+  Free     0   
The SCP Foundation DB fr nn5n                            1,000+  Free     0   
iHoroscope - 2018 Daily Horoscope & Astrology       10,000,000+  Free     0   

                                                   Content Rating  \
App                                                                 
Photo Editor & Candy Camera & Grid & ScrapBook 

In [45]:
# Remove a column
df_google_apps_index.drop(["Category_bis","Android Ver"], axis=1)

Category  \
App                                                                       
Photo Editor & Candy Camera & Grid & ScrapBook           ART_AND_DESIGN   
Coloring book moana                                      ART_AND_DESIGN   
U Launcher Lite – FREE Live Cool Themes, Hide Apps       ART_AND_DESIGN   
Sketch - Draw & Paint                                    ART_AND_DESIGN   
Pixel Draw - Number Art Coloring Book                    ART_AND_DESIGN   
...                                                                 ...   
Sya9a Maroc - FR                                                 FAMILY   
Fr. Mike Schmitz Audio Teachings                                 FAMILY   
Parkinson Exercices FR                                          MEDICAL   
The SCP Foundation DB fr nn5n                       BOOKS_AND_REFERENCE   
iHoroscope - 2018 Daily Horoscope & Astrology                 LIFESTYLE   

                                                    Rating Reviews  \
App                                                                  
Photo Editor & Candy Camera & Grid & ScrapBook         4.1     159   
Coloring book moana                                    3.9     967   
U Launcher Lite – FREE Live Cool Themes, Hide Apps     4.7   87510   
Sketch - Draw & Paint                                  4.5  215644   
Pixel Draw - Number Art Coloring Book                  4.3     967   
...                                                    ...     ...   
Sya9a Maroc - FR                                       4.5      38   
Fr. Mike Schmitz Audio Teachings                       5.0       4   
Parkinson Exercices FR                                 NaN       3   
The SCP Foundation DB fr nn5n                          4.5     114   
iHoroscope - 2018 Daily Horoscope & Astrology          4.5  398307   

                                                                  Size  \
App                                                                      
Photo Editor & Candy Camera & Grid & ScrapBook                     19M   
Coloring book moana                                                14M   
U Launcher Lite – FREE Live Cool Themes, Hide Apps                8.7M   
Sketch - Draw & Paint                                              25M   
Pixel Draw - Number Art Coloring Book                             2.8M   
...                                                                ...   
Sya9a Maroc - FR                                                   53M   
Fr. Mike Schmitz Audio Teachings                                  3.6M   
Parkinson Exercices FR                                            9.5M   
The SCP Foundation DB fr nn5n                       Varies with device   
iHoroscope - 2018 Daily Horoscope & Astrology                      19M   

                                                       Installs  Type Price  \
App                                                                           
Photo Editor & Candy Camera & Grid & ScrapBook          10,000+  Free     0   
Coloring book moana                                    500,000+  Free     0   
U Launcher Lite – FREE Live Cool Themes, Hide Apps   5,000,000+  Free     0   
Sketch - Draw & Paint                               50,000,000+  Free     0   
Pixel Draw - Number Art Coloring Book                  100,000+  Free     0   
...                                                         ...   ...   ...   
Sya9a Maroc - FR                                         5,000+  Free     0   
Fr. Mike Schmitz Audio Teachings                           100+  Free     0   
Parkinson Exercices FR                                   1,000+  Free     0   
The SCP Foundation DB fr nn5n                            1,000+  Free     0   
iHoroscope - 2018 Daily Horoscope & Astrology       10,000,000+  Free     0   

                                                   Content Rating  \
App                                                                 
Photo Editor & Candy Camera & Grid & ScrapBook 

### Remove null values in dataframe

In [67]:
# count null in dataframe df_google_apps
df_google_apps.isnull().sum()

# dropo all rows with null values
df_google_apps_no_NaN = df_google_apps.dropna()
df_google_apps_no_NaN.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

### Sort dataframe 

In [68]:
df_google_apps_no_NaN.sort_values(by='Rating',ascending=False)

App            Category  \
1038                           Mindvalley U Tallinn 2018              EVENTS   
9517                                             Ek Vote        PRODUCTIVITY   
9427                                             ei Calc               TOOLS   
7367                       Startupticker.ch News, Events  NEWS_AND_MAGAZINES   
9444   Kolkata News:Anandbazar Patrika,ei samay&AllRa...  NEWS_AND_MAGAZINES   
...                                                  ...                 ...   
7427                                      CJ DVD Rentals       COMMUNICATION   
10591   Lottery Ticket Checker - Florida Results & Lotto               TOOLS   
7383                                      Thistletown CI        PRODUCTIVITY   
7144                                       CB Mobile Biz             FINANCE   
625                              House party - live chat              DATING   

       Rating Reviews  Size Installs  Type Price Content Rating  \
1038      5.0       1   21M     100+  Free     0       Everyone   
9517      5.0      43  6.2M     500+  Free     0       Everyone   
9427      5.0       2   19M      10+  Free     0       Everyone   
7367      5.0       4   10M     100+  Free     0       Everyone   
9444      5.0      10  5.0M     100+  Free     0       Everyone   
...       ...     ...   ...      ...   ...   ...            ...   
7427      1.0       5   13M     100+  Free     0       Everyone   
10591     1.0       3   41M     500+  Free     0       Everyone   
7383      1.0       1  6.6M     100+  Free     0       Everyone   
7144      1.0       3  8.4M     500+  Free     0       Everyone   
625       1.0       1  9.2M      10+  Free     0     Mature 17+   

                 Genres       Last Updated Current Ver   Android Ver  
1038             Events       July 3, 2018       1.0.5    4.4 and up  
9517       Productivity   November 7, 2017         1.1  4.0.3 and up  
9427              Tools   October 12, 2015       1.2.2    2.3 and up  
7367   News & Magazines      July 23, 2018       2.0.0    4.4 and up  
9444   News & Magazines      July 14, 2018         1.0  4.0.3 and up  
...                 ...                ...         ...           ...  
7427      Communication    October 6, 2017         1.0    4.1 and up  
10591             Tools  December 12, 2017         1.0    4.2 and up  
7383       Productivity     March 15, 2018        41.9    4.1 and up  
7144            Finance  February 22, 2016    4.4.1255    4.0 and up  
625              Dating      July 31, 2018        3.52  4.0.3 and up  

[9360 rows x 13 columns]

In [69]:
# Check type of all dataframe column
df_google_apps_no_NaN.dtypes

df_google_apps_no_NaN.describe(include="all")

App Category       Rating Reviews                Size    Installs  \
count     9360     9360  9360.000000    9360                9360        9360   
unique    8190       33          NaN    5990                 413          19   
top     ROBLOX   FAMILY          NaN       2  Varies with device  1,000,000+   
freq         9     1746          NaN      83                1637        1576   
mean       NaN      NaN     4.191838     NaN                 NaN         NaN   
std        NaN      NaN     0.515263     NaN                 NaN         NaN   
min        NaN      NaN     1.000000     NaN                 NaN         NaN   
25%        NaN      NaN     4.000000     NaN                 NaN         NaN   
50%        NaN      NaN     4.300000     NaN                 NaN         NaN   
75%        NaN      NaN     4.500000     NaN                 NaN         NaN   
max        NaN      NaN     5.000000     NaN                 NaN         NaN   

        Type Price Content Rating Genres    Last Updated         Current Ver  \
count   9360  9360           9360   9360            9360                9360   
unique     2    73              6    115            1299                2638   
top     Free     0       Everyone  Tools  August 3, 2018  Varies with device   
freq    8715  8715           7414    732             319                1415   
mean     NaN   NaN            NaN    NaN             NaN                 NaN   
std      NaN   NaN            NaN    NaN             NaN                 NaN   
min      NaN   NaN            NaN    NaN             NaN                 NaN   
25%      NaN   NaN            NaN    NaN             NaN                 NaN   
50%      NaN   NaN            NaN    NaN             NaN                 NaN   
75%      NaN   NaN            NaN    NaN             NaN                 NaN   
max      NaN   NaN            NaN    NaN             NaN                 NaN   

       Android Ver  
count         9360  
unique          31  
top     4.1 and up  
freq          2059  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN

In [78]:
# Replace values in a column
df_google_apps_no_NaN['Installs_bis'] = df_google_apps_no_NaN['Installs'].str.replace('+','').str.replace(',','').astype(int)
df_google_apps_no_NaN
df_google_apps_no_NaN['Reviews'] = df_google_apps_no_NaN['Reviews'].astype(int)
df_google_apps_no_NaN.describe()

/var/folders/8t/_zpznyq52g12p_gphjl4pq8c0000gn/T/ipykernel_86765/2985738643.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_google_apps_no_NaN['Installs_bis'] = df_google_apps_no_NaN['Installs'].str.replace('+','').str.replace(',','').astype(int)
/var/folders/8t/_zpznyq52g12p_gphjl4pq8c0000gn/T/ipykernel_86765/2985738643.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_google_apps_no_NaN['Reviews'] = df_google_apps_no_NaN['Reviews'].astype(int)


Rating       Reviews  Installs_bis
count  9360.000000  9.360000e+03  9.360000e+03
mean      4.191838  5.143767e+05  1.790875e+07
std       0.515263  3.145023e+06  9.126637e+07
min       1.000000  1.000000e+00  1.000000e+00
25%       4.000000  1.867500e+02  1.000000e+04
50%       4.300000  5.955000e+03  5.000000e+05
75%       4.500000  8.162750e+04  5.000000e+06
max       5.000000  7.815831e+07  1.000000e+09